---
title: "Are Grinnellians Dateable?"
output: html_document
date: '2024-05-01'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)

theme_set(theme_bw())

## Better histograms
gh <- function(bins = 10) {
  geom_histogram(color = 'black', fill = 'gray80', bins = bins)
}

## Bootstrapping function
bootstrap <- function(x, statistic, n = 1000L) {
  bs <- replicate(n, {
    sb <- sample(x, replace = TRUE)
    statistic(sb)
  })
  data.frame(Sample = seq_len(n), 
             Statistic = bs)
}

# read in file
dateability <- read.csv("https://raw.githubusercontent.com/jaysonkunkel/STA-209-final/main/grinnell-dateability.csv")

# copy of data without some NA
data <- dateability %>% filter(dateability$Date.ability != "N/A")

# convert from character to numeric
data$Date.ability <- as.integer(data$Date.ability)
data$Duration_long <- as.numeric(data$Duration_long)
data$Duration_short <- as.numeric(data$Duration_short)

# add number of sexual partners and total partners
data <- data %>% mutate(Sexual = Hookups + Situationships + One_night)
data <- data %>% mutate(Total_partners = Romantic + Sexual)
```

# Dateability plots

```{r}
ggplot(data, aes(Date.ability))+
  gh(bins = 15)

# dateability by gender
ggplot(data, aes(Date.ability, fill = Gender)) +
  geom_bar(position = "stack") +
  labs(x = "Dateability") + 
  scale_x_continuous(breaks = seq(0, 10, by = 1))

# dateability by age
ggplot(data, aes(Date.ability))+
  geom_boxplot()+
  facet_wrap("Age")

# dateability by major
ggplot(data, aes(Date.ability, fill = Academic_Div)) +
  geom_bar(position = "fill") +
  labs(x = "Dateability") + 
  scale_x_continuous(breaks = seq(0, 10, by = 1))

# dateability by orientation
ggplot(data, aes(Date.ability, fill = Orientation)) +
  geom_bar(position = "dodge", color = "black") +
  labs(x = "Dateability") + 
  scale_x_continuous(breaks = seq(0, 10, by = 1))

# dateability by number of total partners
ggplot(data, aes(Date.ability, fill = as.character(Total_partners))) +
  geom_bar(position = "fill", color = "black") +
  labs(x = "Dateability") + 
  scale_x_continuous(breaks = seq(0, 10, by = 1))

```

# Other stuff

```{r}
# dateability by gender
ggplot(data, aes(Date.ability))+
  gh(bins = 15)+
  facet_wrap("Gender")

# first date by sexual orientation
ggplot(data, aes(First_date, fill = Orientation))+
  geom_bar(position = "fill")

# histograms of romantic and sexual partners
ggplot(data, aes(Romantic))+
  gh(bins = 10)

ggplot(data, aes(sexual))+
  gh(bins = 15)

# first date by major
ggplot(data, aes(First_date, fill = Academic_Div))+
  geom_bar(position = "dodge")

# predict shortest relationship with orientation
lm(Duration_short ~ Orientation, data) %>% summary()
```

# Bootstrapping

```{r}
# bootstrap the average dateability
set.seed(123)
dateability_boot <- bootstrap(data$Date.ability, mean)
ggplot(dateability_boot, aes(Statistic)) + 
  gh(bins = 15) +
  labs(x = "Dateability")
mean(dateability_boot$Statistic)

# bootstrap the average number of romantic partners
set.seed(123)
romantic_boot <- bootstrap(data$Romantic, mean)
ggplot(romantic_boot, aes(Statistic)) + 
  gh(bins = 15) +
  labs(x = "Romantic Partners")
mean(romantic_boot$Statistic)

# bootstrap the average number of sexual partners
set.seed(123)
sexual_boot <- bootstrap(data$Sexual, mean)
ggplot(sexual_boot, aes(Statistic)) + 
  gh(bins = 15) +
  labs(x = "Sexual Partners")
mean(sexual_boot$Statistic)

# bootstrap the average number of total partners
set.seed(123)
total_boot <- bootstrap(data$Total_partners, mean)
ggplot(total_boot, aes(Statistic)) + 
  gh(bins = 15) +
  labs(x = "Total Partners")
mean(total_boot$Statistic)


## bootstrap the average longest and shortest relationship
set.seed(123)
longest_boot <- bootstrap(data$Duration_long, mean)
mean(longest_boot$Statistic)

set.seed(123)
shortest_boot <- bootstrap(data$Duration_short, mean)
mean(shortest_boot$Statistic)

ggplot(longest_boot, aes(Statistic)) + 
  gh(bins = 15) +
  labs(x = "Longest Relationship in Weeks")

ggplot(shortest_boot, aes(Statistic)) + 
  gh(bins = 15) +
  labs(x = "Shortest Relationship in Weeks")
```

# Random

```{r}
# proportion of romantic:sexual partners between gender

data <- data %>% mutate(rom_to_sex = Romantic/Sexual)

ggplot(data, aes(x = Gender)) +
  geom_bar(position = "dodge")

# ignores cases where people have 0 sexual partners
b <- bootstrap(is.finite(data$rom_to_sex), mean)

ggplot(b, aes(Statistic)) +
  gh(bins = 15)


with(data, table(Gender, Total_partners))
```

# Google Doc

```{r}
# correlation between origin and number of partners

lm(Romantic ~ Origin, data) %>% summary()
lm(Sexual ~ Origin, data) %>% summary()
lm(Total_partners ~ Origin, data) %>% summary()
# only had 2 countryside - one had 9 romantic

ggplot(data, aes(Origin, Romantic)) +
  geom_jitter() +
  geom_smooth(method = lm, se = FALSE)

ggplot(data, aes(Origin, Sexual)) +
  geom_jitter() +
  geom_smooth(method = lm, se = FALSE)

aov(Romantic ~ Origin, data) %>% summary()
aov(Romantic ~ Origin, data) %>% TukeyHSD()
# diffs: Small town-Countryside, Suburban-Countryside, Unsure-Countryside, Urban/Metropolitan City-Countryside

aov(Sexual ~ Origin, data) %>% summary()
aov(Total_partners ~ Origin, data) %>% summary()
```

```{r}
# does gender play a role in the distribution of romantic and sexual partners
#prop test

lm(is.finite(rom_to_sex) ~ Gender, data) %>% summary()
lm(is.finite(rom_to_sex) ~ Orientation, data) %>% summary()
lm(is.finite(rom_to_sex) ~ Academic_Div, data) %>% summary()

aov(is.finite(rom_to_sex) ~ Gender, data) %>% summary()
aov(is.finite(rom_to_sex) ~ Orientation, data) %>% summary()
aov(is.finite(rom_to_sex) ~ Academic_Div, data) %>% summary()

ggplot(data, aes(Gender, is.finite(rom_to_sex))) +
  geom_jitter() +
  geom_smooth(method = lm, se = FALSE)
```

```{r}
# how does sexual orientation affect dating outcome
aov(Total_partners ~ Orientation, data) %>% summary()

aov(Duration_long ~ Orientation, data) %>% summary()
aov(Duration_short ~ Orientation, data) %>% summary()

aov(Sexual ~ Orientation, data) %>% summary()
aov(Romantic ~ Orientation, data) %>% summary()

aov(Duration_long ~ First_date, data) %>% summary()
aov(Duration_short ~ First_date, data) %>% summary()
```

```{r}
# tests on self-rated dateability (does gender or major play a role in how you rate yourself)
# comments indicate statistical significance

aov(Date.ability ~ Gender, data) %>% summary()
aov(Date.ability ~ Academic_Div, data) %>% summary()
aov(Date.ability ~ Orientation, data) %>% summary
aov(Date.ability ~ as.character(Sexual), data) %>% summary()
aov(Date.ability ~ as.character(Total_partners), data) %>% summary()

aov(Date.ability ~ as.character(Age), data) %>% summary()
aov(Date.ability ~ as.character(Age), data) %>% TukeyHSD()
# groups: 23-19, 23-20, 23-21, 23-22
# however, we only had a few 23 y/o, so this may not be actually significant

aov(Date.ability ~ as.character(Romantic), data) %>% summary()
aov(Date.ability ~ as.character(Romantic), data) %>% TukeyHSD()
# difference between 3 and 0 romantic partners

lm(Date.ability ~ Romantic, data) %>% summary()
lm(Date.ability ~ factor(Romantic), data) %>% summary()

lm(Date.ability ~ Age, data) %>% summary()
lm(Date.ability ~ factor(Age), data) %>% summary()
```

# Front slide + others

```{r}
first date spot based on orientation

# first date by sexual orientation
ggplot(data, aes(First_date, fill = Orientation))+
  geom_bar(position = "fill") +
  labs(x = "First Date Choice")
```

# Fucking around

```{r}

library(ggplot2)
library(gridExtra)

data_male <- data %>% filter(data$Gender == "Male")

set.seed(123)
male_boot_romantic <- bootstrap(data_male$Romantic, mean)
male_rom <- ggplot(male_boot_romantic, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Romantic Partners for Males")
male_rom

set.seed(123)
male_boot_sexual <- bootstrap(data_male$Sexual, mean)
male_sex <- ggplot(male_boot_sexual, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Sexual Partners for Males")
male_sex

set.seed(123)
male_boot_total <- bootstrap(data_male$Total_partners, mean)
male_total <- ggplot(male_boot_total, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Total Partners for Males")
male_total

# -------------------------------------------------------------------------------------------------

data_female <- data %>% filter(data$Gender == "Female")

set.seed(123)
female_boot_romantic <- bootstrap(data_female$Romantic, mean)
female_rom <- ggplot(female_boot_romantic, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Romantic Partners for Females")
female_rom

set.seed(123)
female_boot_sexual <- bootstrap(data_female$Sexual, mean)
female_sex <- ggplot(female_boot_sexual, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Sexual Partners for Females")
female_sex

set.seed(123)
female_boot_total <- bootstrap(data_female$Total_partners, mean)
female_total <- ggplot(female_boot_total, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Total Partners for Females")
female_total

# -------------------------------------------------------------------------------------------------

data_nb <- data %>% filter(data$Gender == "Non-binary / third gender")

set.seed(123)
nb_boot_romantic <- bootstrap(data_nb$Romantic, mean)
nb_rom <- ggplot(nb_boot_romantic, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Romantic Partners for Gender Non-conforming")
nb_rom

set.seed(123)
nb_boot_sexual <- bootstrap(data_nb$Sexual, mean)
nb_sex <- ggplot(nb_boot_sexual, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Sexual Partners for Gender Non-conforming")
nb_sex

set.seed(123)
nb_boot_total <- bootstrap(data_nb$Total_partners, mean)
nb_total <- ggplot(nb_boot_total, aes(Statistic)) + 
       gh(bins = 15) +
       labs(x = "Total Partners for Gender Non-conforming")
nb_total

# -------------------------------------------------------------------------------------------------

grid.arrange(male_sex, female_sex, nb_sex)
grid.arrange(male_rom, female_rom, nb_rom)
grid.arrange(male_total, female_total, nb_total)

# -------------------------------------------------------------------------------------------------

# Build dataset with different distributions
dat <- data.frame(
  type = c( "Male_rom", "Female_rom"),
  value = c( male_boot_total$Statistic, female_boot_total$Statistic)
)

p <- dat %>%
  ggplot( aes(x = value, fill = type)) +
    geom_histogram( color="#e9ecef", alpha=0.5, position = 'identity') +
    scale_fill_manual(values=c("red", "blue"))
p
```







